import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    searchContainer: {
        paddingTop: 50,
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: "#ffffff",
        borderBottomWidth: 1,
        borderBottomColor: "#e8e8e8",
    },
    search: {
        marginTop: 8,
        paddingHorizontal: 16,
        paddingBottom: 12,
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
    },

    row: {
        display: "flex",
        flexDirection: "row",
    },
    container: {
        display: "flex",
        flexDirection: "column",
        flex: 1,
        width: "100%",
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: "#e8e8e8",
    },
    titleAndMenu: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        flex: 1,
    },
    title: {
        fontSize: 28,
        fontWeight: "700",
    },
    headerButtonGroup: {
        flexDirection: "row",
        gap: 12,
        alignItems: "center",
    },
    headerButton: {
        fontSize: 14,
        fontWeight: "600",
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    menuContainer: {
        fontSize: 20,
        fontWeight: "600",
        color: "#666",
        padding: 8,
    },
    itemDetails: {
        borderRadius: 12,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 10,
        marginTop: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 3,
    },
    nameQuantity: {
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
    },
    itemType: {
        fontSize: 12,
        fontWeight: "600",
        marginBottom: 4,
    },
    itemName: {
        fontSize: 17,
        fontWeight: "700",
        flex: 1,
    },
    itemQuantity: {
        fontSize: 14,
        fontWeight: "500",
        marginLeft: 12,
    },
    expirationLocation: {
        justifyContent: "space-between",
        alignItems: "center",
    },
    itemExpiration1: {
        color: "#888",
        fontSize: 13,
        fontWeight: "400",
    },
    itemExpiration2: {
        color: "#dc3545",
        fontSize: 13,
        fontWeight: "700",
    },
    itemExpiration3: {
        color: "#ff9800",
        fontSize: 13,
        fontWeight: "600",
    },
    itemLocation: {
        fontSize: 13,
        fontWeight: "500",
        marginLeft: 12,
    },
    mainContainer: {
        paddingVertical: 0,
        paddingBottom: 80,
    },
    editItemNameInput: {
        fontSize: 16,
        fontWeight: "600",
        color: "#1a1a1a",
        marginBottom: 8,
    },
    editItemLocationInput: {
        fontSize: 13,
        fontWeight: "500",
        color: "#666",
    },
    editItemQuantityInput: {
        fontSize: 14,
        fontWeight: "500",
        color: "#555",
        marginLeft: 12,
        width: 50,
    },
    modal: {
        backgroundColor: "#ffffff",
        marginHorizontal: 12,
        marginVertical: 8,
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#e0e0e0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
        gap: 12,
    },
    input: {
        borderWidth: 1,
        borderColor: "#e8e8e8",
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        color: "#1a1a1a",
        marginBottom: 8,
    },
    deleteHint: {
        fontSize: 12,
        color: "#999",
        fontStyle: "italic",
        marginTop: 8,
        textAlign: "center",
    },
});

export default styles;
