import { StyleSheet } from 'react-native';
import { colors } from '@/screens/components/styles/colors';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingTop: 4,
        width: '100%',
    },
    header: {
        alignItems: 'center',
        marginBottom: 22,
    },
    compactHeader: {
        width: '100%',
        marginBottom: 12,
        paddingHorizontal: 6,
    },
    compactTitle: {
        fontSize: 28,
        fontWeight: '800',
        color: colors.textPrimary,
        marginBottom: 4,
        letterSpacing: 0.2,
    },
    compactDescription: {
        color: colors.textSecondary,
        fontSize: 15,
        lineHeight: 21,
    },
    logo: {
        width: 80,
        height: 80,
        marginBottom: 12,
        resizeMode: 'contain',
    },
    title: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#215a2a',
        marginBottom: 4,
        letterSpacing: 1,
    },
    description: {
        fontSize: 16,
        color: '#4b7e50',
        marginBottom: 8,
    },
    form: {
        width: '100%',
        backgroundColor: '#ffffff',
        borderRadius: 18,
        borderWidth: 1,
        borderColor: colors.borderLight,
        paddingHorizontal: 18,
        paddingTop: 16,
        paddingBottom: 14,
        shadowColor: '#102913',
        shadowOpacity: 0.1,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 7 },
        elevation: 4,
        marginBottom: 14,
    },
    input: {
        marginBottom: 12,
    },
    text: {
        fontSize: 13,
        color: colors.textSecondary,
        marginBottom: 6,
        fontWeight: '700',
        letterSpacing: 0.35,
    },
    textInput: {
        height: 52,
        borderColor: colors.borderLight,
        borderWidth: 1,
        borderRadius: 13,
        paddingHorizontal: 14,
        backgroundColor: '#fff9f4',
        fontSize: 16,
        color: colors.textPrimary,
    },
    button: {
        backgroundColor: colors.accent,
        borderRadius: 13,
        paddingVertical: 15,
        alignItems: 'center',
        marginTop: 8,
        width: '100%',
        shadowColor: '#1a5223',
        shadowOpacity: 0.16,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
        elevation: 3,
    },
    buttonText: {
        color: '#fff',
        fontSize: 16.5,
        fontWeight: '700',
        letterSpacing: 0.3,
    },
    footer: {
        display: 'flex',
        flexDirection: 'row',
        marginTop: 12,
        alignItems: 'center',
    },
    formFooter: {
        marginTop: 12,
        alignItems: 'center',
        width: '100%',
    },
    forgotPassword: {
        color: colors.accentDark,
        fontSize: 12,
        marginTop: 10,
        textAlign: 'center',
        fontWeight: '500',
    },
    // footerText: {
    //     fontSize: 14,
    //     color: '#388e3c',
    //     fontWeight: '500',
    // },
    // footerLink: {
    //     color: '#2e7d32',
    //     fontSize: 14,
    //     fontWeight: 'bold',
    //     textDecorationLine: 'underline',
    // },
});

export default styles;