import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingTop: 6,
        width: '100%',
    },
    header: {
        alignItems: 'center',
        marginBottom: 22,
    },
    compactHeader: {
        width: '100%',
        marginBottom: 14,
        paddingHorizontal: 8,
    },
    compactTitle: {
        fontSize: 26,
        fontWeight: '800',
        color: '#153a1a',
        marginBottom: 4,
    },
    compactDescription: {
        color: '#4f7053',
        fontSize: 15,
        lineHeight: 21,
    },
    logo: {
        width: 80,
        height: 80,
        marginBottom: 12,
        resizeMode: 'contain',
    },
    title: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#215a2a',
        marginBottom: 4,
        letterSpacing: 1,
    },
    description: {
        fontSize: 16,
        color: '#4b7e50',
        marginBottom: 8,
    },
    form: {
        width: '100%',
        backgroundColor: '#ffffff',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#d3e5d6',
        paddingHorizontal: 18,
        paddingTop: 18,
        paddingBottom: 16,
        shadowColor: '#102913',
        shadowOpacity: 0.09,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 5 },
        elevation: 4,
        marginBottom: 18,
    },
    input: {
        marginBottom: 14,
    },
    text: {
        fontSize: 13,
        color: '#315c36',
        marginBottom: 7,
        fontWeight: '700',
        letterSpacing: 0.4,
    },
    textInput: {
        height: 50,
        borderColor: '#cfe3d1',
        borderWidth: 1,
        borderRadius: 14,
        paddingHorizontal: 14,
        backgroundColor: '#f8fcf8',
        fontSize: 16,
        color: '#143217',
    },
    button: {
        backgroundColor: '#276f30',
        borderRadius: 14,
        paddingVertical: 15,
        alignItems: 'center',
        marginTop: 10,
        width: '100%',
    },
    buttonText: {
        color: '#fff',
        fontSize: 17,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    footer: {
        display: 'flex',
        flexDirection: 'row',
        marginTop: 12,
        alignItems: 'center',
    },
    formFooter: {
        marginTop: 12,
        alignItems: 'center',
        width: '100%',
    },
    forgotPassword: {
        color: '#388e3c',
        fontSize: 12,
        marginTop: 10,
        textAlign: 'center',
        textDecorationLine: 'underline',
        fontWeight: '500',
    },
    // footerText: {
    //     fontSize: 14,
    //     color: '#388e3c',
    //     fontWeight: '500',
    // },
    // footerLink: {
    //     color: '#2e7d32',
    //     fontSize: 14,
    //     fontWeight: 'bold',
    //     textDecorationLine: 'underline',
    // },
});

export default styles;