import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 108,
    paddingTop: 10,
    gap: 10,
  },
  welcomeCard: {
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  welcomeEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  welcomeTitle: {
    fontSize: 31,
    fontWeight: "700",
    lineHeight: 37,
    marginTop: 4,
  },
  welcomeSubtitle: {
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  quickActionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  dashboardHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  dashboardHeaderCopy: {
    flex: 1,
  },
  moduleEditorButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  moduleBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  moduleBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  moduleBadgeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  modulePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 8,
  },
  modulePickerTextWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  modulePickerIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(76,175,80,0.12)",
  },
  modulePickerTitle: {
    fontSize: 13,
    fontWeight: "700",
  },
  modulePickerDesc: {
    fontSize: 11,
    marginTop: 2,
    lineHeight: 15,
  },
  modulePickerBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  modulePickerBadgeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  quickActionButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  quickActionText: {
    fontSize: 13,
    fontWeight: "600",
  },
  nutritionCard: {
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
    gap: 10,
  },
  nutritionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  nutritionHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  nutritionEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  nutritionTitle: {
    fontSize: 24,
    fontWeight: "700",
    marginTop: 2,
  },
  nutritionTargetButton: {
    borderWidth: 1,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  nutritionTargetButtonText: {
    fontSize: 12,
    fontWeight: "600",
  },
  calorieHeroRow: {
    flexDirection: "row",
    gap: 10,
  },
  calorieHeroBlock: {
    flex: 1,
    minWidth: 0,
  },
  calorieHeroPrimaryBlock: {
    flex: 1.18,
  },
  calorieHeroSecondaryBlock: {
    flex: 0.82,
    alignItems: "flex-end",
    paddingRight: 4,
  },
  calorieHeroValue: {
    fontSize: 28,
    fontWeight: "700",
    lineHeight: 34,
  },
  calorieHeroLabel: {
    fontSize: 12,
    marginTop: 2,
  },
  progressTrack: {
    height: 10,
    borderRadius: 999,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
  },
  progressCaption: {
    fontSize: 12,
  },
  macroStack: {
    gap: 8,
    marginTop: 2,
  },
  macroRow: {
    gap: 5,
  },
  macroLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  macroLabel: {
    fontSize: 13,
    fontWeight: "600",
  },
  macroValue: {
    fontSize: 12,
  },
  macroTrack: {
    height: 8,
  },
  nutritionMealSection: {
    marginTop: 4,
    gap: 8,
  },
  nutritionSectionTitle: {
    fontSize: 14,
    fontWeight: "700",
  },
  nutritionMealRow: {
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  nutritionMealBody: {
    flex: 1,
  },
  nutritionMealTitle: {
    fontSize: 14,
    fontWeight: "600",
  },
  nutritionMealMeta: {
    fontSize: 12,
    marginTop: 2,
  },
  nutritionMealCalories: {
    fontSize: 13,
    fontWeight: "700",
  },
  todayCard: {
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  todayTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 10,
  },
  todayEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  todayStatChip: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  todayStatText: {
    fontSize: 12,
    fontWeight: "700",
  },
  todayTitle: {
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 32,
  },
  todaySubtitle: {
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
  },
  todoSection: {
    marginTop: 14,
    gap: 8,
  },
  todoItem: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    gap: 10,
  },
  todoItemIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  todoItemBody: {
    flex: 1,
  },
  todoItemTitle: {
    fontSize: 14,
    fontWeight: "600",
  },
  todoItemMeta: {
    fontSize: 12,
    marginTop: 2,
  },
  todoEmpty: {
    fontSize: 13,
    lineHeight: 18,
  },
  calendarCard: {
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  calendarNavButton: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarMonthLabel: {
    fontSize: 17,
    fontWeight: "700",
  },
  weekdayRow: {
    flexDirection: "row",
  },
  weekdayLabel: {
    width: "14.28%",
    textAlign: "center",
    fontSize: 12,
    fontWeight: "700",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    rowGap: 8,
  },
  dayCellBlank: {
    width: "14.28%",
    height: 50,
  },
  dayCell: {
    width: "14.28%",
    height: 50,
    borderWidth: 1,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  dayCellText: {
    fontSize: 14,
    fontWeight: "700",
  },
  dayCountBadge: {
    position: "absolute",
    bottom: 4,
    minWidth: 18,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  dayCountText: {
    fontSize: 10,
    fontWeight: "700",
  },
  selectedDateHeader: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  selectedDateTitle: {
    fontSize: 15,
    fontWeight: "700",
    flex: 1,
  },
  addPlanButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
  },
  addPlanButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  planItem: {
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  planItemMain: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 8,
  },
  planItemBody: {
    flex: 1,
  },
  planItemTitle: {
    fontSize: 14,
    fontWeight: "600",
  },
  planItemMeta: {
    fontSize: 12,
    marginTop: 1,
  },
  emptyPlanText: {
    fontSize: 13,
  },
  missingCard: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 8,
  },
  missingHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  missingTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  missingTitle: {
    fontSize: 13,
    fontWeight: "700",
  },
  addAllMissingButton: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  addAllMissingText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "700",
  },
  missingEmpty: {
    fontSize: 12,
    lineHeight: 17,
  },
  missingItemRow: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 9,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  missingItemBody: {
    flex: 1,
  },
  missingItemName: {
    fontSize: 13,
    fontWeight: "600",
  },
  missingItemMeta: {
    fontSize: 11,
    marginTop: 2,
  },
  addMissingButton: {
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  addMissingText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  modalBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  modalCard: {
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 8,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "700",
    flex: 1,
  },
  modalTitleWrap: {
    flex: 1,
    gap: 2,
  },
  modalSubtitle: {
    fontSize: 12,
    lineHeight: 17,
  },
  foodModalCard: {
    maxHeight: "86%",
    minHeight: "70%",
  },
  foodModalScroll: {
    flexGrow: 0,
  },
  foodModalContent: {
    paddingBottom: 14,
    gap: 12,
  },
  discoveryPanel: {
    minHeight: 170,
    justifyContent: "flex-start",
  },
  targetFieldWrap: {
    marginBottom: 10,
    gap: 6,
  },
  targetFieldLabel: {
    fontSize: 13,
    fontWeight: "600",
  },
  targetFieldInput: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 14,
  },
  targetActionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  targetActionButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  targetActionText: {
    fontSize: 13,
    fontWeight: "600",
  },
  targetPrimaryActionText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
  },
  manualFoodRow: {
    flexDirection: "row",
    gap: 10,
  },
  manualFoodAmountWrap: {
    flex: 1,
  },
  manualFoodUnitWrap: {
    width: 92,
  },
  unitChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  unitChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  unitChipText: {
    fontSize: 12,
    fontWeight: "600",
  },
  quickSection: {
    gap: 8,
  },
  quickSectionTitle: {
    fontSize: 13,
    fontWeight: "700",
  },
  quickChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  quickChipText: {
    fontSize: 12,
    fontWeight: "600",
  },
  suggestionRow: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  suggestionBody: {
    flex: 1,
  },
  suggestionTitle: {
    fontSize: 14,
    fontWeight: "600",
  },
  suggestionMeta: {
    fontSize: 12,
    marginTop: 2,
  },
  pantryTrackingCard: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 8,
    minHeight: 152,
  },
  pantryTrackingHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  pantryTrackingStatus: {
    fontSize: 14,
    fontWeight: "600",
  },
  pantryTrackingMeta: {
    fontSize: 12,
    lineHeight: 18,
  },
  previewCard: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 4,
  },
  previewEyebrow: {
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  previewCalories: {
    fontSize: 22,
    fontWeight: "700",
  },
  previewMacros: {
    fontSize: 12,
    lineHeight: 18,
  },
  foodModalFooter: {
    borderTopWidth: 1,
    marginTop: 10,
    paddingTop: 12,
  },
  manualFoodHint: {
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 4,
  },
  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
  },
  modalList: {
    paddingTop: 10,
    paddingBottom: 6,
    gap: 8,
  },
  modalRecipeRow: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  modalRecipeText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
  },
  modalEmpty: {
    textAlign: "center",
    paddingVertical: 16,
    fontSize: 13,
  },
});
