import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 108,
    paddingTop: 10,
    gap: 10,
  },
  welcomeCard: {
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  welcomeEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  welcomeTitle: {
    fontSize: 31,
    fontWeight: "700",
    lineHeight: 37,
    marginTop: 4,
  },
  welcomeSubtitle: {
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  quickActionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  quickActionButton: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  quickActionText: {
    fontSize: 13,
    fontWeight: "600",
  },
  todayCard: {
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  todayTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 10,
  },
  todayEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  todayStatChip: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  todayStatText: {
    fontSize: 12,
    fontWeight: "700",
  },
  todayTitle: {
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 32,
  },
  todaySubtitle: {
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
  },
  todoSection: {
    marginTop: 14,
    gap: 8,
  },
  todoItem: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    gap: 10,
  },
  todoItemIcon: {
    width: 28,
    height: 28,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  todoItemBody: {
    flex: 1,
  },
  todoItemTitle: {
    fontSize: 14,
    fontWeight: "600",
  },
  todoItemMeta: {
    fontSize: 12,
    marginTop: 2,
  },
  todoEmpty: {
    fontSize: 13,
    lineHeight: 18,
  },
  calendarCard: {
    borderWidth: 1,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  calendarNavButton: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarMonthLabel: {
    fontSize: 17,
    fontWeight: "700",
  },
  weekdayRow: {
    flexDirection: "row",
  },
  weekdayLabel: {
    width: "14.28%",
    textAlign: "center",
    fontSize: 12,
    fontWeight: "700",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    rowGap: 8,
  },
  dayCellBlank: {
    width: "14.28%",
    height: 50,
  },
  dayCell: {
    width: "14.28%",
    height: 50,
    borderWidth: 1,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  dayCellText: {
    fontSize: 14,
    fontWeight: "700",
  },
  dayCountBadge: {
    position: "absolute",
    bottom: 4,
    minWidth: 18,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  dayCountText: {
    fontSize: 10,
    fontWeight: "700",
  },
  selectedDateHeader: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  selectedDateTitle: {
    fontSize: 15,
    fontWeight: "700",
    flex: 1,
  },
  addPlanButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
  },
  addPlanButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  planItem: {
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  planItemMain: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 8,
  },
  planItemBody: {
    flex: 1,
  },
  planItemTitle: {
    fontSize: 14,
    fontWeight: "600",
  },
  planItemMeta: {
    fontSize: 12,
    marginTop: 1,
  },
  emptyPlanText: {
    fontSize: 13,
  },
  missingCard: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 8,
  },
  missingHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  missingTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  missingTitle: {
    fontSize: 13,
    fontWeight: "700",
  },
  addAllMissingButton: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  addAllMissingText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "700",
  },
  missingEmpty: {
    fontSize: 12,
    lineHeight: 17,
  },
  missingItemRow: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 9,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  missingItemBody: {
    flex: 1,
  },
  missingItemName: {
    fontSize: 13,
    fontWeight: "600",
  },
  missingItemMeta: {
    fontSize: 11,
    marginTop: 2,
  },
  addMissingButton: {
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  addMissingText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  modalCard: {
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 8,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "700",
    flex: 1,
  },
  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
  },
  modalList: {
    paddingTop: 10,
    paddingBottom: 6,
    gap: 8,
  },
  modalRecipeRow: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  modalRecipeText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
  },
  modalEmpty: {
    textAlign: "center",
    paddingVertical: 16,
    fontSize: 13,
  },
});
