import { StyleSheet } from "react-native";

export default StyleSheet.create({
  shellDecorLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  shellCircleTop: {
    position: "absolute",
    top: -130,
    right: -95,
    width: 230,
    height: 230,
    borderRadius: 115,
  },
  shellCircleBottom: {
    position: "absolute",
    bottom: -160,
    left: -120,
    width: 260,
    height: 260,
    borderRadius: 130,
  },
  shellContentLayer: {
    flex: 1,
    overflow: "hidden",
    zIndex: 2,
  },
  blankScreen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  blankText: {
    fontSize: 24,
    color: '#999',
  },
  bottomTabContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderTopWidth: 0,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    overflow: "hidden",
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 12,
  },
  tabButton: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    minHeight: 56,
  },
  tabIcon: {
    justifyContent: "center",
    alignItems: "center",
    gap: 4,
  },
  tabIconPill: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 44,
  },
  iconText: {
    // kept for compatibility
  },
  iconTextActive: {
    // kept for compatibility
  },
  tabLabel: {
    fontSize: 10,
    fontWeight: "500",
    letterSpacing: 0.3,
  },
  tabLabelActive: {
    fontWeight: "700",
  },
  centerButton: {
    width: 58,
    height: 58,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    shadowColor: "#FF8A3D",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 10,
  },
  centerButtonIcon: {
    fontSize: 36,
    fontWeight: "700",
  },
  socialShell: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  socialCard: {
    width: "100%",
    borderRadius: 26,
    paddingHorizontal: 20,
    paddingVertical: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 5,
  },
  socialIconWrap: {
    width: 62,
    height: 62,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  socialTitle: {
    fontSize: 23,
    fontWeight: "800",
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  socialText: {
    fontSize: 14,
    textAlign: "center",
    lineHeight: 21,
  },
  kitchenSwitcher: {
    position: "absolute",
    top: 92,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 4,
    paddingVertical: 4,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 22,
  },
  kitchenSwitcherOption: {
    minHeight: 32,
    borderRadius: 999,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  kitchenSwitcherText: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.1,
  },
});
