import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 58,
    paddingBottom: 96,
    gap: 12,
  },
  headerRow: {
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 2,
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    width: "100%",
  },
  headerMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  addFriendButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  addFriendText: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  title: {
    fontSize: 30,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  subtitle: {
    fontSize: 13,
    lineHeight: 19,
  },
  tag: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tagText: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  emptyCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
    gap: 8,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "700",
  },
  emptySub: {
    textAlign: "center",
    lineHeight: 20,
  },
  card: {
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  cardHead: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  userPressArea: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
    marginRight: 8,
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#ffefe1",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  avatarText: {
    color: "#d86f21",
    fontWeight: "800",
  },
  user: {
    fontSize: 14,
    fontWeight: "700",
  },
  handle: {
    fontSize: 12,
    marginTop: 2,
  },
  readyBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  readyText: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  recipeTitle: {
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 5,
  },
  note: {
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 10,
  },
  timestampRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 10,
  },
  timestampPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  timestampText: {
    fontSize: 11,
    fontWeight: "600",
  },
  cover: {
    width: "100%",
    height: 180,
    borderRadius: 14,
    marginBottom: 10,
  },
  snippetTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
  },
  snippetTitle: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  photoRow: {
    gap: 10,
    paddingRight: 8,
    marginBottom: 10,
  },
  photoCard: {
    width: 190,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#f7f7f7",
  },
  photo: {
    width: "100%",
    height: 140,
  },
  photoCardSmall: {
    width: 136,
  },
  photoSmall: {
    height: 92,
  },
  photoLabelWrap: {
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  photoLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#4f4f4f",
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    maxWidth: "100%",
  },
  actionText: {
    fontSize: 12,
    fontWeight: "700",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    paddingHorizontal: 18,
    justifyContent: "center",
  },
  modalCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
  },
  modalSubtitle: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
  },
  modalRecipeImage: {
    width: "100%",
    height: 170,
    borderRadius: 12,
    marginTop: 10,
    marginBottom: 8,
  },
  modalMeta: {
    fontSize: 12,
    marginBottom: 10,
    fontWeight: "600",
  },
  modalTimestampLine: {
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 10,
    fontWeight: "600",
  },
  modalSectionTitle: {
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  modalBulletText: {
    fontSize: 13,
    lineHeight: 19,
  },
  modalInstructionText: {
    fontSize: 13,
    lineHeight: 19,
  },
  modalInput: {
    marginTop: 12,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 11,
    paddingVertical: 9,
    fontSize: 14,
  },
  modalActions: {
    marginTop: 12,
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-end",
  },
  modalButton: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  modalButtonText: {
    fontSize: 13,
    fontWeight: "700",
  },
  modalLoadingText: {
    marginTop: 10,
    marginBottom: 10,
    fontSize: 13,
  },
  modalList: {
    marginTop: 10,
    marginBottom: 10,
    maxHeight: 260,
  },
  modalListItem: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 10,
    padding: 8,
  },
  commentItem: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
  },
  commentAuthor: {
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
  },
  commentText: {
    fontSize: 13,
    lineHeight: 19,
  },
  commentComposerRow: {
    marginTop: 8,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  commentInput: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 11,
    paddingVertical: 9,
    fontSize: 14,
  },
  commentSendButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  profileChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  profileChip: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  profileChipText: {
    fontSize: 12,
    fontWeight: "700",
  },
  profileRecipeThumb: {
    width: 44,
    height: 44,
    borderRadius: 8,
    marginRight: 10,
  },
});
