import { StyleSheet } from 'react-native';
import { colors } from '@/screens/components/styles/colors';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        position: 'relative',
        backgroundColor: colors.bgLight,
    },
    topGlow: {
        position: 'absolute',
        top: -100,
        right: -60,
        width: 250,
        height: 250,
        borderRadius: 125,
        backgroundColor: colors.accentMuted,
    },
    bottomGlow: {
        position: 'absolute',
        bottom: -96,
        left: -84,
        width: 260,
        height: 260,
        borderRadius: 130,
        backgroundColor: '#ffe9d6',
    },
    content: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 16,
        paddingVertical: 24,
    },
    welcomeCard: {
        backgroundColor: '#ffffff',
        borderRadius: 24,
        padding: 24,
        borderWidth: 1,
        borderColor: colors.borderLight,
        shadowColor: '#0c2a0e',
        shadowOpacity: 0.13,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 10 },
        elevation: 6,
    },
    welcomeEyebrow: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 1.2,
        color: colors.accentDark,
        marginBottom: 10,
    },
    welcomeTitle: {
        fontSize: 32,
        lineHeight: 40,
        fontWeight: '800',
        color: colors.textPrimary,
        marginBottom: 12,
    },
    welcomeDescription: {
        fontSize: 15.5,
        lineHeight: 23,
        color: colors.textSecondary,
        marginBottom: 20,
    },
    featureList: {
        marginBottom: 26,
        gap: 12,
    },
    featureItemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    featureItem: {
        color: colors.textSecondary,
        fontSize: 14.5,
        lineHeight: 20,
        flex: 1,
    },
    primaryButton: {
        backgroundColor: colors.accent,
        borderRadius: 14,
        alignItems: 'center',
        paddingVertical: 15,
        marginBottom: 12,
    },
    primaryButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 0.2,
    },
    secondaryButton: {
        backgroundColor: '#fff4eb',
        borderRadius: 14,
        alignItems: 'center',
        paddingVertical: 15,
        borderWidth: 1,
        borderColor: '#c7ddc9',
    },
    secondaryButtonText: {
        color: colors.accentDark,
        fontSize: 16,
        fontWeight: '700',
        letterSpacing: 0.2,
    },
    authShell: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderRadius: 24,
        borderWidth: 1,
        borderColor: colors.borderLight,
        overflow: 'hidden',
        shadowColor: '#0c2a0e',
        shadowOpacity: 0.13,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 10 },
        elevation: 6,
    },
    authHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 18,
        paddingTop: 16,
        paddingBottom: 12,
    },
    backAction: {
        color: colors.accentDark,
        fontSize: 14.5,
        fontWeight: '700',
    },
    authHeaderTitle: {
        color: colors.textPrimary,
        fontSize: 17,
        fontWeight: '700',
    },
    headerSpacer: {
        width: 36,
    },
    switcher: {
        flexDirection: 'row',
        backgroundColor: '#fff2e4',
        borderRadius: 999,
        marginHorizontal: 18,
        marginBottom: 10,
        padding: 4,
    },
    switcherOption: {
        flex: 1,
        borderRadius: 999,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 11,
    },
    switcherOptionActive: {
        backgroundColor: colors.accent,
    },
    switcherText: {
        fontSize: 14.5,
        fontWeight: '700',
        color: colors.textMuted,
    },
    switcherTextActive: {
        color: '#ffffff',
    },
    formContainer: {
        flex: 1,
        paddingHorizontal: 12,
        paddingBottom: 12,
    },
});

export default styles;