import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        position: 'relative',
        backgroundColor: '#eef4ee',
    },
    topGlow: {
        position: 'absolute',
        top: -110,
        right: -70,
        width: 260,
        height: 260,
        borderRadius: 130,
        backgroundColor: '#d7ead8',
    },
    bottomGlow: {
        position: 'absolute',
        bottom: -110,
        left: -90,
        width: 280,
        height: 280,
        borderRadius: 140,
        backgroundColor: '#cbe2cd',
    },
    content: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 18,
        paddingVertical: 24,
    },
    welcomeCard: {
        backgroundColor: '#ffffff',
        borderRadius: 22,
        padding: 22,
        borderWidth: 1,
        borderColor: '#d9e8da',
        shadowColor: '#0c2a0e',
        shadowOpacity: 0.12,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
        elevation: 5,
    },
    welcomeEyebrow: {
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 1,
        color: '#2f6e37',
        marginBottom: 10,
    },
    welcomeTitle: {
        fontSize: 30,
        lineHeight: 37,
        fontWeight: '800',
        color: '#133217',
        marginBottom: 12,
    },
    welcomeDescription: {
        fontSize: 15,
        lineHeight: 22,
        color: '#426845',
        marginBottom: 18,
    },
    featureList: {
        marginBottom: 24,
        gap: 10,
    },
    featureItem: {
        color: '#2c5531',
        fontSize: 14,
        lineHeight: 20,
        paddingLeft: 2,
    },
    primaryButton: {
        backgroundColor: '#2f7a38',
        borderRadius: 12,
        alignItems: 'center',
        paddingVertical: 14,
        marginBottom: 10,
    },
    primaryButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '700',
    },
    secondaryButton: {
        backgroundColor: '#e7f2e8',
        borderRadius: 12,
        alignItems: 'center',
        paddingVertical: 14,
        borderWidth: 1,
        borderColor: '#c7ddc9',
    },
    secondaryButtonText: {
        color: '#2f6e37',
        fontSize: 16,
        fontWeight: '700',
    },
    authShell: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderRadius: 24,
        borderWidth: 1,
        borderColor: '#d9e8da',
        overflow: 'hidden',
        shadowColor: '#0c2a0e',
        shadowOpacity: 0.12,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 8 },
        elevation: 5,
    },
    authHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 18,
        paddingTop: 14,
        paddingBottom: 10,
    },
    backAction: {
        color: '#2f6e37',
        fontSize: 14,
        fontWeight: '700',
    },
    authHeaderTitle: {
        color: '#244f2a',
        fontSize: 16,
        fontWeight: '700',
    },
    headerSpacer: {
        width: 36,
    },
    switcher: {
        flexDirection: 'row',
        backgroundColor: '#eef5ef',
        borderRadius: 999,
        marginHorizontal: 18,
        marginBottom: 8,
        padding: 4,
    },
    switcherOption: {
        flex: 1,
        borderRadius: 999,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
    },
    switcherOptionActive: {
        backgroundColor: '#2f7a38',
    },
    switcherText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#527157',
    },
    switcherTextActive: {
        color: '#ffffff',
    },
    formContainer: {
        flex: 1,
        paddingHorizontal: 10,
        paddingBottom: 10,
    },
});

export default styles;