import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  backButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    paddingTop: 50,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: "600",
  },
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 100,
    paddingTop: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 4,
    color: "#333",
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 20,
  },
  preferencesContainer: {
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 24,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  preferenceItem: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  itemInfo: {
    gap: 8,
  },
  itemType: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  displayRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  daysDisplay: {
    fontSize: 16,
    fontWeight: "700",
    color: "#4CAF50",
  },
  editHint: {
    fontSize: 12,
    color: "#bbb",
    fontStyle: "italic",
  },
  editingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  daysInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#4CAF50",
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 16,
    fontWeight: "600",
  },
  daysLabel: {
    fontSize: 14,
    color: "#666",
    minWidth: 35,
  },
  checkButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#4CAF50",
  },
  checkButtonText: {
    fontSize: 20,
    color: "#fff",
    fontWeight: "bold",
  },
  buttonContainer: {
    gap: 10,
    marginBottom: 24,
  },
  saveButton: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
    backgroundColor: "#4CAF50",
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  resetButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#999",
  },
  resetButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  infoBox: {
    backgroundColor: "#f0f8ff",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#4CAF50",
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 6,
    color: "#333",
  },
  infoText: {
    fontSize: 13,
    lineHeight: 18,
    color: "#666",
  },
});
